options:

  substitution_option: 'ALLOW_LOOSE'
  
substitions:
  
  # Set these values in build config (for now)
  #_FIREBASE_PROJECT: 
  _FIREBASE_TOKEN: 1/Pc6q5R0yW29SxP8CJgl1grUyZZV_bj0QMOhC9IJv1v7jR4r3g97WBy8dKeT402co
  #_FIREBASE_TOKEN_ENC: 
  #_FIREBASE_TOKEN_KMS_KEY_NAME: 
  #_FIREBASE_TOKEN_KMS_KEYRING_NAME: 
  #_FIREBASE_TOKEN_KMS_SECRET_NAME:

secrets:
- kmsKeyName: projects/${PROJECT_ID}/locations/global/keyRings/${_FIREBASE_TOKEN_KMS_KEYRING_NAME}/cryptoKeys/${__FIREBASE_TOKEN_KMS_KEYRING_NAME}
  secretEnv:
    MY_SECRET: ${_FIREBASE_TOKEN_KMS_SECRET_NAME}

steps:
# Get the 
  
# Build the project using the site specific, firebase hosting preload image
- name: 'gcr.io/[PROJECT_ID]/${_PRELOAD_IMAGE}
  args: [ 'deploy', '-P', '${_FIREBASE_PROJECT}', '--token', '$${_FIREBASE_TOKEN_KMS_SECRET_NAME}' ]
  secretEnv: ['_FIREBASE_TOKEN']
