options:

  substitution_option: 'ALLOW_LOOSE'
  
substitions:
  
  # Set these values in build config (for now)
  #_FIREBASE_PROJECT: 
  _FIREBASE_TOKEN: 1/Pc6q5R0yW29SxP8CJgl1grUyZZV_bj0QMOhC9IJv1v7jR4r3g97WBy8dKeT402co
  #_FIREBASE_TOKEN_ENC: 
  #_FIREBASE_TOKEN_KMS_KEY_NAME: 
  #_FIREBASE_TOKEN_KMS_KEYRING_NAME: 
  #_FIREBASE_TOKEN_KMS_SECRET_NAME:

secrets:
- kmsKeyName: projects/${PROJECT_ID}/locations/global/keyRings/${_FIREBASE_TOKEN_KMS_KEYRING_NAME}/cryptoKeys/${__FIREBASE_TOKEN_KMS_KEYRING_NAME}
  secretEnv:
    MY_SECRET: ${_FIREBASE_TOKEN_KMS_SECRET_NAME}


# substutions:

  # _FIREBASE_PROJECT_DIR=/workspace/project/

steps:

# Create required directories

# mkdir ${_FIREBASE_PROJECT_DIR}

# Clone the firebase project repo
# git -C clone ${_FIREBASE_HOSTING_PROJECT_REPO} (to) /workspace/project/
 
# OR: copy from the preload project to workspace from the preload image (more complicated)
# OR: construct firebase.json from metadata (if there are no rewrite rules}

# Clone the dist to the preloaded firebase project inside the site specific firebase delpoy container
  
# git -C ${_DIST_REPO} (to) /workspace/project/{$_DIST_REPO_FOLDER}

# Build the project using the site specific, firebase hosting preload image
- name: 'gcr.io/[PROJECT_ID]/${_PRELOAD_IMAGE}
  args: [ 'deploy', '-P', '${_FIREBASE_PROJECT_DIR}', '--token', '$${_FIREBASE_TOKEN_KMS_SECRET_NAME}' ]
  secretEnv: ['_FIREBASE_TOKEN']
